### ISSUE TITLE
GPAW_SETUP_PATH is corrupted when ls is set with coloring enabled

### ISSUE THREAD

**Issue by thomasaarholt** [conda-forge/gpaw-feedstock#20]
So this one took me a while.

I've got `ls` aliased to `ls --color` in my .bash_profile.

The following line prepends and appends colouring the the path string set at $GPAW_SETUP_PATH. 
https://github.com/conda-forge/gpaw-feedstock/blob/7c3396521450e4b4ffa2d6fda5bb6cf96638dc5c/recipe/activate.sh#L1

This meant that gpaw wasn't finding my files, despite everything seeming fine.

```
(gpaw) [thomasaar@ml7 ~]$ echo $GPAW_SETUP_PATH
/itf-fi-ml/home/thomasaar/.conda/envs/gpaw/share/gpaw

(gpaw) [thomasaar@ml7 ~]$ cd $GPAW_SETUP_PATH
-bash: cd: $'\E[0m\E[38;5;33m/itf-fi-ml/home/thomasaar/.conda/envs/gpaw/share/gpaw\E[0m': No such file or directory
```

Not sure how to suggest a more robust path setting mechanism.

**Comment by marcindulak** [comment]
Maybe the value can be just hard-coded to `${CONDA_PREFIX}/share/gpaw`?

```
export GPAW_SETUP_PATH="${CONDA_PREFIX}/share/gpaw"
```

If more logic provided by `ls` is really necessary (what are the uses-cases?), then maybe hard-coding `/bin/ls` is an option?

```
export GPAW_SETUP_PATH=$(/bin/ls -rd ${CONDA_PREFIX}/share/gpaw | head -n 1) 
```

**Comment by thomasaarholt** [comment]
I think the first option makes the most sense, unless @jan-janssen has any input?
