### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by vladislavivanistsev** [conda-forge/gpaw-feedstock#38]
### Comment:

Could you please add some "release notes" about new packages?
It is visible that new packages are added to conda-forge, yet it is not obvious what has changed as the GPAW version remains the same.

**Comment by gdonval** [comment]
I am not sure what you want. Is there even a release note mechanism in conda? If so, I don't mind adding stuff there but you can get the same kind of information in the pull-request section.

**Comment by vladislavivanistsev** [comment]
Do you mean something like this thread: https://github.com/conda-forge/gpaw-feedstock/pull/36 ? – It looks like you have updated numpy version and created an osx version.

I am curious whether you can make releases in this github repository, where you briefly describe the changes. For example, I would be happy to see when you add a version with libxc 6.0.0 or openmpi 5.0.0.

**Comment by gdonval** [comment]
> and created an osx version

Not quite yet: this is the general `aarch64` version for Linux. :)

I'm all for providing an Osx version (both for Intel and Arm). The groundwork is done but I don't have time to do it and manage the aftermath just now. I could have a look by the end of next week.

> I am curious whether you can make releases in this github repository

I don't think that is as useful as you think for the moment: all dependencies are either determined by `conda-smithy` (the `conda-forge` builder) or `conda-build` (typically will chose the latest versions available). We have very little control on it and multiple versions could be provided from the same repository version.

For instance the numpy version bump you've seen has been automatically set by `conda-smithy` (we have nothing to do with it). Plus it is just used at build time: `conda` will typically install the latest numpy version possible when installing `gpaw`. So the bump is practically a non-event.

The version of `openmpi` or `libxc` is chosen on the fly at build time by `conda-build`. So even if Conda Forge (as a governing entity) tolerates releases, I am not sure you would get any more exciting information than "bumped to the latest gpaw version".

So libxc 6 or openmpi 5 should naturally come in the repo when they are ready (libxc 6 is not in conda yet and openmpi 5 has not been released yet).

**Comment by gdonval** [comment]
osx version exists now
